# Generated by Django 4.2.2 on 2023-07-14 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_alter_availability_options'),
        ('news', '0005_alter_news_animal_alter_news_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='animals.animal'),
        ),
    ]
