# Generated by Django 4.1.3 on 2023-01-13 06:11

from django.db import migrations
from django.core.management import call_command


def load_fixture(apps, schema_editor):
    call_command('loaddata', 'News')


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_news_animal')
    ]

    operations = [
        migrations.RunPython(load_fixture)
    ]
