# Generated by Django 4.2.2 on 2023-07-03 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0002_shelter_contact'),
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Animals',
            new_name='Animal',
        ),
    ]
