# Generated by Django 4.2.2 on 2023-07-15 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_alter_availability_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
