# Generated by Django 4.2.2 on 2023-07-16 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_animal_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['date_entered']},
        ),
    ]
