# Generated by Django 4.2.2 on 2023-07-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0008_animal_image_alter_animal_breed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.ImageField(default='placeholder_animal.jpg', upload_to='animal_pics'),
        ),
    ]
