# Generated by Django 4.2.2 on 2023-07-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0009_alter_animal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.ImageField(default='placeholder_animal.png', upload_to='animal_pics'),
        ),
    ]
