# Generated by Django 4.2.2 on 2023-07-23 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0010_alter_animal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='disposition',
            field=models.ManyToManyField(blank=True, to='animals.disposition'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.ImageField(blank=True, default='placeholder_animal.png', upload_to='animal_pics'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='size',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='animals.size'),
        ),
    ]
