# Generated by Django 4.1.3 on 2023-01-13 06:11

from django.db import migrations
from django.core.management import call_command


def load_fixture(apps, schema_editor):
    call_command('loaddata', 'Availability')
    call_command('loaddata', 'Species')
    call_command('loaddata', 'Breed')
    call_command('loaddata', 'Disposition')
    call_command('loaddata', 'Size')
    call_command('loaddata', 'Animals')


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0011_alter_animal_disposition_alter_animal_image_and_more'),
        ('shelters', '0007_load_sample_data')
    ]

    operations = [
        migrations.RunPython(load_fixture)
    ]
